# Generated by Django 5.0 on 2023-12-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tamtour_startlistmanager", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wettspieler",
            old_name="is_soloduo",
            new_name="is_group",
        ),
        migrations.AlterField(
            model_name="wettspieler",
            name="is_group",
            field=models.BooleanField(default=False, verbose_name="Gruppe?"),
        ),
        migrations.RenameField(
            model_name="wettspieler",
            old_name="soloduoname",
            new_name="group_members",
        ),
        migrations.AlterField(
            model_name="wettspieler",
            name="group_members",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Gruppenmitglieder"
            ),
        ),
        migrations.AlterField(
            model_name="wettspieler",
            name="name",
            field=models.CharField(max_length=50, verbose_name="(Gruppen-)Name"),
        ),
        migrations.AddField(
            model_name="startliste",
            name="visible",
            field=models.BooleanField(
                default=True,
                verbose_name="In Schnittstelle sichtbar?",
                help_text="Soll diese Startliste in der JSON-Schnittstelle verfügbar und "
                "somit im Overlay-Control-Panel sichtbar sein? "
                "(Die JSON-Schnittstelle ist ohne Authentifizierung zugänglich!)",
            ),
        ),
    ]
