# Generated by Django 5.0.6 on 2024-05-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tamtour_startlistmanager", "0002_better_group_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="komposition",
            name="typ",
            field=models.CharField(
                choices=[
                    ("T", "Tambour"),
                    ("P", "Pfeifer"),
                    ("SD", "Solo Duo (Piccolo / Tambour)"),
                ],
                default="T",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="komposition",
            name="klakomtitel",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="komposition",
            name="komponist",
            field=models.CharField(max_length=75),
        ),
        migrations.AlterUniqueTogether(
            name="komposition",
            unique_together={("typ", "klakomtitel")},
        ),
    ]
