# Generated by Django 5.0.7 on 2024-07-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tamtour_startlistmanager",
            "0003_komposition_typ_alter_komposition_klakomtitel_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="wettspielkategorie",
            name="default_composition_type",
            field=models.CharField(
                choices=[
                    ("T", "Tambour"),
                    ("P", "Pfeifer"),
                    ("SD", "Solo Duo (Piccolo / Tambour)"),
                ],
                default="T",
                max_length=5,
                verbose_name="Kompositionstyp",
            ),
        ),
    ]
