# Generated by Django 5.0.7 on 2024-07-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tamtour_startlistmanager",
            "0004_wettspielkategorie_default_composition_type",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="startliste",
            name="overlay_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="In Startlisten-Overlay verwendet",
                max_length=30,
                verbose_name="Overlay-Titel",
            ),
        ),
        migrations.AlterField(
            model_name="startliste",
            name="beschreibung",
            field=models.TextField(
                blank=True, default="", help_text="Wird auf Startliste gedruckt"
            ),
        ),
    ]
