# Generated by Django 5.2rc1 on 2025-04-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tamtour_startlistmanager",
            "0006_apikey_ytaccount_ytstreamgroup_ytstream_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="startliste",
            name="visible",
            field=models.BooleanField(
                default=True,
                help_text="Soll diese Startliste in der JSON-Schnittstelle verfügbar und somit im Overlay-Control-Panel sichtbar sein?",
                verbose_name="In Schnittstelle sichtbar?",
            ),
        ),
        migrations.AlterField(
            model_name="ytstreamstarttimelog",
            name="content",
            field=models.CharField(max_length=75),
        ),
    ]
