# Generated by Django 5.2.4 on 2025-10-19 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tamtour_startlistmanager", "0007_alter_startliste_visible_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ytstreamstarttimelog",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
